apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: erezazariya/service-registry:latest
          ports:
            - containerPort: 5001  # microservice1 port
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 5001  # Expose microservice1 on port 5001 internally
      targetPort: 5001
  type: ClusterIP
