apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
        - name: main-server
          image: erezazariya/server:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVICE_REGISTRY_URL
              value: "http://microservice1.default.svc.cluster.local:5001" # microservice1 port 5001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: main-server
spec:
  selector:
    app: main-server
  ports:
    - protocol: TCP
      port: 5000  # Expose main server on port 5000
      targetPort: 5000
  type: LoadBalancer  # Change to NodePort
