name: Build and Test Server

on:
  push:
    branches:
      - 'release'
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies for server
        working-directory: ./server
        run: npm install
      - name: Compile TypeScript
        working-directory: ./server
        run: npx tsc
